spring.application.name=api-gateway

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Enable Gateway Service Discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Static Routes Configuration
spring.cloud.gateway.routes[0].id=farmer-service
spring.cloud.gateway.routes[0].uri=lb://FARMER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/farmer/**

spring.cloud.gateway.routes[1].id=crop-service
spring.cloud.gateway.routes[1].uri=lb://CROP-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/crop/**


spring.main.web-application-type=reactive